// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migraciones / introspect: preferí session/direct (5432). Runtime usa
    // DATABASE_URL en transaction mode (6543) vía el adapter de PrismaPg.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
